### ISSUE TITLE
customizable maximal triangle count for triangulation

### ISSUE THREAD

**Issue by mkraenz** [proSingularity/shredder_flow#44]
RuppertAdapter allows to set the maximum number of triangles.
- [ ] There should be a GUI element similar to #43.
- [ ] solve the corresponding part of #84 along with this

**Comment by proSingularity** [comment]
In my opinion the triangle count should be more important, i.e. if both #43 and #44 are specified, only #44 is respected (maybe even tell the user that specifying both is stupid)
